// Generated by https://quicktype.io

import { ParsedUrlQuery } from "querystring";
import { ImageDto } from "../auth/auth.interface";
import { Status } from "../property/property.interface";

export interface CreateFndChatDto {
  id: number;
  store_id: number;
  user_request_id: number;
  type: string;
  status: number;
  last_message_id: null;
  created_at: string;
  updated_at: string;
  participants: Participant[];
}

export interface Participant {
  user: User;
}

export interface User {
  id: number;
  full_name: string;
  profile: Profile;
}

export interface Profile {
  id: number;
  user_id: number;
  admin_id: null;
  name: string;
  meta: null;
  thumbnail: string;
  type: number;
  path: string;
  bucket: string;
  region: null;
  end_point: string;
  created_at: string;
  updated_at: string;
}

// Generated by https://quicktype.io

export interface LastMessage {
  text: string;
  created_at: string;
}

export interface Recipient {
  profile: Profile;
  full_name: string;
}

export interface Profile {
  id: number;
  user_id: number;
  admin_id: null;
  name: string;
  meta: null;
  thumbnail: string;
  type: number;
  path: string;
  bucket: string;
  region: null;
  end_point: string;
  created_at: string;
  updated_at: string;
}

// Generated by https://quicktype.io

export interface NewSingleChatDto {
  id: number;
  text: string | null;
  created_at: string;
  deleted_at: string | null;
  participant_id: number;
  media?: Media | null;
  clientMessageId?: string;
  deliveryStatus?: "sending" | "sent" | "failed";
}

export interface Media {
  id: number;
  user_id: number;
  admin_id: null;
  user_role: string;
  name: string;
  meta: null;
  thumbnail: string;
  type: number;
  path: string;
  bucket: string;
  region: null;
  end_point: string;
  medium: string;
  alt: null;
  created_at: Date;
  updated_at: Date;
  deleted_at: null;
}

export interface SingleChatDto {
  id: number;
  chatroom_id: number;
  participant_id: number;
  text: string;
  media_id: null;
  post_id: number | null;
  created_at: string;
  updated_at: string;
  media: Cover;
  post: ChatPostDto | null;
  participant: Participant;
}

// Generated by https://quicktype.io

export interface ChatPostDto {
  id: number;
  title: string;
  product_code: string;
  cover: Cover;
}

export interface Cover {
  id: number;
  user_id: number;
  admin_id: null;
  name: string;
  meta: null;
  thumbnail: string;
  type: number;
  path: string;
  bucket: string;
  region: null;
  end_point: string;
  created_at: string;
  updated_at: string;
}

export interface Participant {
  user: User;
}

export interface User {
  id: number;
  full_name: string;
  profile: Profile;
}

export interface Profile {
  id: number;
  user_id: number;
  admin_id: null;
  name: string;
  meta: null;
  thumbnail: string;
  type: number;
  path: string;
  bucket: string;
  region: null;
  end_point: string;
  created_at: string;
  updated_at: string;
}

// Generated by https://quicktype.io

export interface TicketsDto {
  id: number;
  user_id: number;
  status: Status;
  title: string;
  message: string;
  reply: null;
  reply_at: null;
  created_at: string;
  updated_at: string;
  deleted_at: null;
}

// Generated by https://quicktype.io

export interface ContentDto {
  category: Category;
  contents: Content[];
}

export interface Category {
  id: number;
  title: string;
  description: string;
  key: string;
  image_id: null;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  image: any;
}

export interface Content {
  id: number;
  title: string;
  key: string;
  small_text: string;
  full_text: string;
  feature_image_id: null;
  is_active: boolean;
  category_id: number;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  attachments: any[];
  feature_image: null;
}

export interface NewMessageDto {
  id: number;
  chatroom_id: number;
  participant_id: number;
  text: string;
  media_id: null;
  post_id: null;
  created_at: string;
  updated_at: string;
  media: null;
  post: null;
  participant: Participant;
}

export interface Participant {
  user: User;
}

export interface ProductChatType {
  title: string;
  image_location: ImageDto;
  id: number;
  description: string;
  product?: {
    image_location: ImageDto;

    title: string;
    description: string;
    id: number;
  };
}
export interface ReduxProductChatType {
  params: { [key: string]: ProductChatType };
}

export interface OtpQuery extends ParsedUrlQuery {
  id: string;
  product?: string;
}

export interface ChatRoomCrreateDto {
  chatroom_id: string;
}

export interface PropertyChatDto {
  id: number;
  slug: string;
  title: string;
  feature_image: ImageDto;
  is_expired: boolean;
  owner: { user: { id: number } };
}

export interface SingleChatDetailsDto {
  id: string;
  unread_count: number | string;
  property: PropertyChatDto;
  self: Recipient;
  recipient: Recipient;
  is_recipient_online: boolean;
  is_blocked: boolean;
}

export interface Recipient {
  participant_id: number;
  user_id: number;
  role: string;
  user_mobile_number: string;
}

export interface SendMessageReeturnDto {
  chatroom_id: string;
  message: NewSingleChatDto;
}

export interface Message {
  id: number;
  participant: number;
  text: string;
  created_at: Date;
  media: null;
}

export interface ChatMessagesPageDto {
  data: NewSingleChatDto[];
}

export interface ChatRealtimeMessageEvent {
  chatroom_id: string;
  message: NewSingleChatDto;
}

export interface ChatRealtimeDeleteEvent {
  chatroom_id: string;
  message_id?: number;
}

export interface ChatTypingEvent {
  chatroom_id: string;
  is_typing: boolean;
}

export interface SendChatMessageDto {
  id: string | number;
  text: string;
  media_id?: number;
  clientMessageId?: string;
  optimisticMedia?: Media;
}

export interface BaseContentsDto {
  data: Datum[];
  meta: Meta;
  subcategories: any[];
}

export interface Datum {
  id: number;
  title: string;
  slug: string;
  key: null;
  small_text: string;
  full_text: null;
  feature_image_id: null;
  is_active: boolean;
  category_id: number;
  order: null;
  html: null;
  view_count: number;
  link: string;
  video_id: null;
  fields: Fields;
  seo: Fields;
  created_at: Date;
  updated_at: Date;
  category: Category;
  feature_image: any;
  attachments: any[];
  video: null;
  questions: any[];
}

export interface Fields {}

export interface Meta {
  total: number;
  lastPage: number;
  currentPage: number;
  perPage: number;
  prev: null;
  next: null;
}

export interface ChatListDto {
  id: number;
  uuid: string;
  last_update: string;
  last_message: LastMessageDto;
  property_id: number;
  property_title: string;
  other_side_mobile: string;
  property_image: ImageDto;
  unread_count: number | string;
}

export interface LastMessageDto {
  id: number;
  chatroom_id: number;
  participant_id: number;
  text: string;
  media_id: null;
  third_party: null;
  created_at: Date;
  updated_at: Date;
  deleted_at: null;
}
