// Generated by https://quicktype.io

import { ImageDto } from "../auth/auth.interface";

export interface ContentByKeyDto {
  id: number;
  title: string;
  slug: string;
  key: string;
  small_text: null;
  full_text: string;
  feature_image_id: null;
  is_active: boolean;
  category_id: null;
  order: null;
  html: string;
  view_count: number;
  link: null;
  video_id: null;
  fields: Fields;
  seo: Fields;
  created_at: string;
  updated_at: string;
  category: null;
  feature_image: null;
  video: null;
  attachments: any[];
}

export interface Fields {}

export interface ContentDto {
  id: number;
  title: string;
  slug: null;
  key: null;
  small_text: string;
  full_text: string;
  feature_image_id: null;
  is_active: boolean;
  category_id: number;
  order: null;
  html: string;
  view_count: number;
  link: string;
  video_id: null;
  fields: { [key: string]: string };
  seo: null;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  category: Category;
  feature_image: ImageDto;
  attachments: any[];
}

export interface Category {
  id: number;
  title: string;
  slug: string;
  key: string;
  image_id: null;
  dynamic_fields: null;
  parent_id: null;
  description: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
  parent: null;
  image: ImageDto;
}
