// Generated by https://quicktype.io

export interface ContentByKeyDto {
  id: number;
  title: string;
  slug: string;
  key: string;
  small_text: null;
  full_text: string;
  feature_image_id: null;
  is_active: boolean;
  category_id: null;
  order: null;
  html: string;
  view_count: number;
  link: null;
  video_id: null;
  fields: Fields;
  seo: Fields;
  created_at: string;
  updated_at: string;
  category: null;
  feature_image: null;
  video: null;
  attachments: any[];
}

export interface Fields {}
