"use client";
import { NewSingleChatDto, ProductChatType } from "@/api_services/chat/chat.interface";
import { ChatService } from "@/api_services/chat/chat.service";
import ChatBody from "@/components/chat/ChatBody";
import ChatFooter from "@/components/chat/ChatFooter";
import ChatHeader from "@/components/chat/ChatHeader";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useParams, useSearchParams } from "next/navigation";
import { ParsedUrlQuery } from "querystring";
import { useEffect, useRef, useState } from "react";

import useViewportHeightFix from "@/components/chat/UseViewPortHeight";
import ConfirmModal from "@/components/Modal/ConfirmModal";
import UseIsInViewport from "@/helpers/Observer";
import { useChatStore } from "@/store";
import _STRINGS from "@/utils/LocalStrings";
import isEmpty from "lodash/isEmpty";

// Generated by https://quicktype.io

export interface UserReduxType {
  params: { [key: string]: any };
}

const useOnScreenKeyboardScrollFix = () => {
  useEffect(() => {
    const handleScroll = () => {
      window.scrollTo(0, 0);
    };

    window.addEventListener("scroll", handleScroll);

    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);
};

const Chat = () => {
  const searchparams = useSearchParams();
  // const [showDelete, setShowDelete] = useState(false);

  const { chatNotification, chatDelete, usersStatus, deletedMessage, chatProduct } = useChatStore((state) => state);
  const [isParticipentOnine, setIsParticipentOnline] = useState(false);
  const ref = useRef<HTMLDivElement>(null);
  const bottomerRefer = useRef<HTMLDivElement>(null);
  const { chat_id } = useParams();
  const product = searchparams.get("product");
  const [bodyFirstTime, setBodyFirstTime] = useState(true);
  const [cursor, setCursor] = useState<string | number>(0);
  const [firstTime, setFirstTime] = useState(true);
  const [height, setHeight] = useState<any>("100dvh");
  const [preventer, setpreventer] = useState(true);
  const [refresher, setRefresher] = useState(false);
  const [keyboard, setKeyboard] = useState(false);
  const [data, setData] = useState<NewSingleChatDto[] | []>([]);
  const [productState, setProductState] = useState<null | ProductChatType>(chatProduct ? chatProduct : null);
  const [scrollY, setScrollY] = useState(0);
  const [offSetTop, setOffSetTop] = useState(0);

  useEffect(() => {
    setProductState(chatProduct);
    return () => {
      cancleButton();
    };
  }, [chatProduct]);

  const cancleButton = () => {
    useChatStore.setState({
      chatProduct: null,
    });
    setProductState(null);
  };

  const {
    refetch,
    data: chatDataMessage,
    isLoading,
  } = useQuery({
    queryFn: () => {
      if (chat_id) return ChatService.GetSingleChatMessages({ id: `${chat_id}`, cursor: cursor });
    },

    queryKey: [ChatService?.GET_SNGLE_CHAT_MESSAGES_CACHEKEY, chat_id, cursor, refresher],

    enabled: false,
  });

  useEffect(() => {
    if (!!chatDataMessage?.data) {
      if (cursor == 0) {
        setData(chatDataMessage?.data?.reverse());
      } else {
        const reversedData = chatDataMessage?.data?.reverse();
        setTimeout(() => {
          document.getElementById(data?.[0]?.id)?.scrollIntoView({ behavior: "instant" }), 1;
        });
        setData((x) => [...reversedData, ...x]);
      }
    }
  }, [chatDataMessage]);

  //////////////////////////////////

  const { data: singleChatData } = useQuery({
    queryFn: () => {
      if (chat_id) return ChatService.GetSingleChat({ id: `${chat_id}` });
    },
    queryKey: [ChatService?.GET_SINGLE_CHAT_CACHEKEY, chat_id],

    staleTime: 0,
    gcTime: 0,
  });

  useEffect(() => {
    if (!!singleChatData) {
      if (singleChatData?.is_recipient_online) {
        setIsParticipentOnline(true);
      }
    }
  }, [singleChatData]);

  ///////////////////////

  useEffect(() => {
    if (chat_id) {
      refetch();
    }
  }, [chat_id, cursor, refresher]);

  useEffect(() => {
    if (!!chatNotification && !firstTime) {
      if (chatNotification?.chatroom_id == chat_id) {
        // refetch();
        setData((e) => [...e, chatNotification?.message]);
      }
    }
  }, [chatNotification]);

  useEffect(() => {
    if (data && firstTime) {
      setFirstTime(false);
    }
    if (preventer && data) {
      setTimeout(() => {
        setpreventer(false);
      }, 1000);
    }
  }, [data]);

  const getNextData = () => {
    if (!firstTime && !preventer) {
      if (data?.length % 20 == 0 && !isLoading) {
        setCursor(data[0]?.id);
      }
    }
  };

  const scrollToBottom = () => {
    bottomerRefer.current?.scrollIntoView({ behavior: "instant" });
  };

  useEffect(() => {
    const handleScroll = () => {
      setScrollY(window.scrollY);
    };

    // just trigger this so that the initial state
    // is updated as soon as the component is mounted
    // related: https://stackoverflow.com/a/63408216
    handleScroll();

    window.addEventListener("scroll", handleScroll);
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  useEffect(() => {
    getNextData();
  }, [scrollY]);

  // to get height right
  useViewportHeightFix(setHeight, setOffSetTop);

  const closeDeleteMessage = () => {
    useChatStore.setState({ chatDelete: null });
  };

  useEffect(() => {
    if (!!usersStatus && !!singleChatData) {
      if (singleChatData?.recipient?.user_id == usersStatus?.user_id) {
        setIsParticipentOnline(usersStatus?.is_online);
      }
    }
  }, [usersStatus, singleChatData]);

  useEffect(() => {
    if (!!deletedMessage) {
      setCursor(0);
      setRefresher((e) => !e);
      useChatStore.setState({
        chatDelete: null,
      });
    }
  }, [deletedMessage]);

  const { mutate: deleteMessage, isPending: deleteLoading } = useMutation({
    onSuccess: () => {
      setCursor(0);
      setRefresher((e) => !e);
      closeDeleteMessage();
    },
    mutationFn: ChatService.deleteMessage,
  });
  const { mutate: readChat } = useMutation({ mutationFn: ChatService.chatRead });

  useEffect(() => {
    return () => {
      readChat({ chatId: `${chat_id}` });
    };
  }, []);

  const getNextInView = UseIsInViewport(`getNext`);
  useEffect(() => {
    if (!!getNextInView) {
      getNextData();
    }
  }, [getNextInView]);
  return (
    <div
      ref={ref}
      style={{
        height: "100dvh",
      }}
      className={`chat-container flex flex-col   md:!w-1/2 overflow-y-clip  !bg-neutral-100    max-h-[100dvh] relative col-span-4 `}
      // style={{ height: `${useWindowSize()?.height}px` }}
    >
      <ChatHeader
        is_recipient_online={isParticipentOnine}
        name={singleChatData?.property?.title}
        data={singleChatData}
        image={singleChatData?.property?.feature_image}
        offSetTop={offSetTop}
      />
      {/* {isLoading ? <LottieLoading /> : <></>} */}
      {data ? (
        <ChatBody
          nextIsLoading={isLoading && !isEmpty(data)}
          isLoading={isLoading && isEmpty(data)}
          singleChatData={singleChatData}
          scrollToBottom={scrollToBottom}
          refer={bottomerRefer}
          firstTime={bodyFirstTime}
          setFirstTime={setBodyFirstTime}
          data={data}
        />
      ) : (
        <></>
      )}
      {!firstTime && (
        <ChatFooter
          setData={setData}
          singleChatData={singleChatData}
          callback={() => {
            setHeight(`100dvh`);
          }}
          scrollToBottom={scrollToBottom}
          showProduct={product == "true" ? true : false}
          product={productState}
          cancleButton={cancleButton}
          setKeyboard={setKeyboard}
          keyoard={keyboard}
          chatId={`${chat_id}`}
          setRefresher={setRefresher}
          setCursor={setCursor}
        />
      )}
      <ConfirmModal
        isLoading={deleteLoading}
        onConfirm={() => {
          deleteMessage({ chatId: chatDelete?.id, id: `${chat_id}` });
        }}
        isVisible={!!chatDelete}
        text={_STRINGS.ARE_U_SURE_DELETE_MESSAGE}
        onHide={closeDeleteMessage}
      />
    </div>
  );
};

Chat.getInitialProps = async ({ query }: ParsedUrlQuery) => {
  return { query };
};

export default Chat;
