const token = (name: string) => `rgb(var(--c-${name}) / <alpha-value>)`;

export const semanticColors = {
  page: token("page"),
  surface: token("surface"),
  "surface-muted": token("surface-muted"),
  "surface-hover": token("surface-hover"),
  ink: token("ink"),
  "ink-muted": token("ink-muted"),
  "ink-subtle": token("ink-subtle"),
  link: token("link"),
  action: token("action"),
  "action-hover": token("action-hover"),
  "on-action": token("on-action"),
  selected: token("selected"),
  "on-selected": token("on-selected"),
  "selected-line": token("selected-line"),
  line: token("line"),
  "line-strong": token("line-strong"),
  control: token("control"),
  focus: token("focus"),
  status: {
    danger: token("status-danger"),
    "danger-bg": token("status-danger-bg"),
    "danger-line": token("status-danger-line"),
    success: token("status-success"),
    "success-bg": token("status-success-bg"),
    "success-line": token("status-success-line"),
    warning: token("status-warning"),
    "warning-bg": token("status-warning-bg"),
    "warning-line": token("status-warning-line"),
  },
  overlay: token("overlay"),
} as const;
