import { DESTRUCTION } from "dns";
import { property } from "lodash";

const _STRINGS = {
  CURRENCY: "تومان",
  NO_PRICE: "توافقی",
  TOMAN: "تومان",
  BUCKS: "دلار",
  ALL: "همه",
  RIAL: "ریال",
  ENTER: "ورود",
  ADAD: "عدد",
  NAFAR: "نفر",
  DESTRUCTION: "توضیحات",
  MINUTE: "دقیقه",
  HOUR: "ساعت",
  EMAIL: "ایمیل ",
  PRICE: "قیمت",
  METER: "متر",
  KM: "کیلومتر",
  SPECIALIST: "متخصص",
  SEARCH: "جستجو",
  COUNT: "تعداد",
  HOME: "خانه",
  GENDER: "جنسیت",
  ADD: "آگهی",
  COUNTRY: "کشور",
  JUST_DEPOSIT: "واریز",
  JUST_WITHDRAW: "برداشت",
  TRANSACTIONS: "تراکنش ها",
  MENU: "منو",
  DELETE: "حذف",
  REPLY: "پاسغ",
  MAN: "مرد",
  WOMAN: "زن",
  DATE: "تاریخ",
  TIME: "زمان",
  DETAILS: "جزئیات",
  UNDERSTOOD: "متوجه شدم",
  ENTER_AND_MOVE_ON: "تایید و ادامه",
  FAVS: "علاقمندی ها",
  NODATA_LIST: "آیتمی یافت نشد",
  SHORT_CODE: "کد کامل نمیباشد",
  TOTAL_NAME: "نام و نام خانوادگی",
  NATIONAL_ID: "کد ملی",
  LOREM:
    "   لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهایتنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجودر ارائه راهکارها و شرایط سخت تایپ به پایان رسد.",
  MY_PROFILE: "جایاب من",
  CONNECTING: "در حال اتصال",
  WRONG_NUMBER: " شماره موبایل صحیح نمیباشد",
  ATTENTION: "توجه",
  WORNG_NUMBER: "شماره موبایل صحیح نمیباشد .",
  TERMS: "قوانین و مقررات",
  ENTER_TOUR_MOBILE_NUMBER: "شماره تلفن خود را وارد کنید",
  U_ACCEPTED: "ورود شما به معنای پذیرش",
  SEND_AGAIN: "ارسال مجدد",
  CODE_EXPI_TIME: "اعتبار کد",
  ENTER_FOUR_DIGITS: "کد 4 رقمی ارسال شده به شماره خود را وارد کنید",
  EDIT_NUMBER: "ویرایش شماره",
  CREATE_ADD: "ثبت آگهی",
  CONSULTAMCY: "مشاوران",

  TODAYS_PRICE: "قیمت امروز:",
  VERIFIED: "احراز شده",
  ROOM_COUNTS: "تعداد اتاق:",
  ROOM: "اتاق",
  ROOM_SIZE: "متراژ بنا",
  PROPERTY_LOC: "لوکیشن بنا",
  ONLINE_RESERVE: "رزرو ویلا",
  PERSONAL_INFO: "اطلاعات شخصی",
  YOUR_IMAGE: "عکس شما*",
  PROFILE_IMAGE: " تصویر پروفایل",
  CHECK_CREDENTIOALS: "احراز کد ملی و ادامه",
  REGISTER_PROPERTY: "ثبت ملک",
  PROPERTY_TYPE: "نوع ملک  ",
  ROTATE_PHONE: "لطفا گوشی خود را در حالت عمودی قرار دهید",
};

export default _STRINGS;
