const _STRINGS = {
  TRY_AGAIN: "تلاش دوباره",
  ERROR: "خطایی رخ داده است",
  MESSAGE_SENDING: "در حال ارسال",
  MESSAGE_SEND_FAILED: "ارسال ناموفق",
  CHAT_RECONNECTING: "در حال اتصال مجدد...",
  SANDBOX_OTP: "کد ورود سندباکس",
  CURRENCY: "تومان",
  IMAGE: "تصویر",
  RETURN: "بازگشت",
  EMPTY: "خالی",
  OCCUPIED: "رزرو",
  NO_PRICE: "توافقی",
  TOMAN: "تومان",
  BUCKS: "دلار",
  ALL: "همه",
  RIAL: "ریال",
  CODE: "کد",
  ENTER: "ورود",
  ADAD: "عدد",
  NAFAR: "نفر",
  DESCRIPTION: "توضیحات",
  SECONDS: "ثانیه",
  MINUTE: "دقیقه",
  HOUR: "ساعت",
  EMAIL: "ایمیل ",
  PRICE: "قیمت",
  METER: "متر",
  KM: "کیلومتر",
  SPECIALIST: "متخصص",
  SEARCH: "جستجو",
  COUNT: "تعداد",
  HOME: "خانه",
  GENDER: "جنسیت",
  ADD: "آگهی",
  COUNTRY: "کشور",
  JUST_DEPOSIT: "واریز",
  JUST_WITHDRAW: "برداشت",
  TRANSACTIONS: "تراکنش ها",
  EDIT: "ویرایش",
  MENU: "منو",
  DELETE: "حذف",
  REPLY: "پاسغ",
  MAN: "مرد",
  WOMAN: "زن",
  DATE: "تاریخ",
  TIME: "زمان",
  DETAILS: "جزئیات",
  UNDERSTOOD: "متوجه شدم",
  ENTER_AND_MOVE_ON: "تایید و ادامه",
  FAVS: "علاقمندی ها",
  NODATA_LIST: "آیتمی یافت نشد",
  SHORT_CODE: "کد کامل نمیباشد",
  TOTAL_NAME: "نام و نام خانوادگی",
  NATIONAL_ID: "کد ملی",
  SHARE: "اشتراک گذاری",
  YOUR_TEXT: "متن شما ...",
  FULL_NAME: "نام و نام خانوادگی ",
  XP: "سابقه",
  OWNER: "مالک",
  OWNER_ASSIST: "دستیار میزبان",
  LOGO: "جایاب",
  JAYAB: "Jayab",
  LOREM:
    "   لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهایتنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجودر ارائه راهکارها و شرایط سخت تایپ به پایان رسد.",
  MY_PROFILE: "جایاب من",
  CONNECTING: "در حال اتصال",
  WRONG_NUMBER: " شماره موبایل صحیح نمیباشد",
  ATTENTION: "توجه",
  WORNG_NUMBER: "شماره موبایل صحیح نمیباشد .",
  TERMS: "قوانین و مقررات",
  ENTER_TOUR_MOBILE_NUMBER: "شماره تلفن خود را وارد کنید",
  U_ACCEPTED: "ورود شما به معنای پذیرش",
  SEND_AGAIN: "ارسال مجدد",
  CODE_EXPI_TIME: "اعتبار کد",
  ENTER_FOUR_DIGITS: "کد 4 رقمی ارسال شده به شماره خود را وارد کنید",
  EDIT_NUMBER: "ویرایش شماره",
  CREATE_ADD: "ثبت آگهی",
  CONSULTAMCY: "مشاوران",

  //
  SEARCH_ADD: "جستجوی آگهی",
  CALL: "تماس",
  MESSAGE: "پیامک",
  RECORD_SCORE: "ثبت امتیاز",
  RECORD_CONSULTANT_SCORE: "ثبت امتیاز مشاور",

  TODAYS_PRICE: "قیمت امروز",
  VERIFIED: "احراز شده",
  ROOM_COUNTS: "تعداد اتاق",
  ROOM: "اتاق",
  ROOM_SIZE: "متراژ بنا",
  PROPERTY_LOC: "لوکیشن بنا",
  ONLINE_RESERVE: "رزرو ویلا",
  PERSONAL_INFO: "اطلاعات شخصی",
  YOUR_IMAGE: "عکس شما*",
  PROFILE_IMAGE: " تصویر پروفایل",
  CHECK_CREDENTIOALS: "احراز کد ملی و ادامه",
  REGISTER_PROPERTY: "ثبت ملک",
  PROPERTY_TYPE: "نوع ملک  ",
  ROTATE_PHONE: "لطفا گوشی خود را در حالت عمودی قرار دهید",

  // CONSULTANT
  CONSULTANT_INFO: "اطلاعات مشاور",
  CHOOSE_STATE_AND_CITY: "انتخاب استان و شهر",
  SEARCH_FOR_CONSULTANTS: "جستجوی مشاور",
  CODE_OR_CONSULTANT_NAME: "کد یا نام مشاور",

  CONSULTANT_APPROACHES: "نحوه برخورد مشاور",
  CONSULTANT_RESPONSIBILITY: "مسئولیت پذیری مشاور",
  FOLLOWUP_SPEED_RESPONSE: "سرعت پیگیری و نحوه پاسخگویی",

  USERS_SATISFACTION: "رضایت کاربران",
  OWNERS_SATISFACTION: "رضایت مالکان",

  // footer
  BECOME_HOST: "میزبان شوید",
  DISCOVER_ADS: "مشاهده آگهی ها",
  RECEIVED: "دریفات شده",
  RECORD_CHANGES: "ثبت تغییرات",
  AWAITING_APPROVAL: "در انتظار تایید",
  SUBMIT_REQUEST: "ارسال درخواست",
  CHANGE_OF_CONSULTANT_COMMISSION: "ارسال درخواست",
  IMMEDIATE_CHANGE: "تغییر فوری",
  DISCOUNTED_PRICE_TITLE: "قیمت با تخفیف",
  APPLY_DISCOUNT: "اعمال تخفیف",
  ALL_CITIES: "همه شهرها",

  MINUTES: "دقیقه",
  HOURS: "ساعت",
  PAY: "پرداخت",

  FROM: "از",
  TO: "تا",
  UNIT: "واحد ",

  ADD_TITLE: "عنوان آگهی",
  LAND_AREA: "متراژ زمین",
  PROPERTY_AREA: "متراژ بنا ",
  FLOOR_COUNT: "تعداد طبقات ",
  UNITS_IN_FLOOR: "تعداد واحد در طبقات ",
  FLOOR: "طبقه",
  OWNERSHIP: "نوع مالکیت  ",
  PROVINCE: "استان",
  CITY: "شهر",
  CREATED_AT_YEAR: "سال ساخت ",
  BUILDING_DIRECTION: "جهت ساختمان  ",
  EXACT_ADDRESS: "آدرس دقیق ",
  PROP_EXACT_ADDRESS: " آدرس دقیق ملک",
  CAN_CHAT_SET: "فعال کردن امکان چت",
  LOC_ACCESS: "نمایش موقعیت مکانی به متقاضیان",
  SUBMIT_MOVE_ON: "ثبت و ادامه",
  SELECTED_ADDRESSES: "آدرس های منتخب",
  SEARCH_PLACE: "جستجوی آدرس...",
  SEARCH_PLACE_INPUT: "جستجوی آدرس",
  PROPERTY_LOCATION: "موقعیت مکانی ملک",
  PROPERTY_MEDIA: "تصاویر  ملک",
  PRIMARY_IMAGE: "عکس اصلی",
  FEATURE_IMAGE_NEEDED: "لطفا عکس اصلی را انتخاب کنید.",
  ENV_PATTERN: "بافت محیطی",
  PATTERN: "بافت محیطی",
  ACCESS_ROUTE: "مسیر دسترسی",
  ACCESS_ROUTE_DESC: "توضیحات بافت و مسیر دسترسی",
  NEIGHBORHOOD_TYPE: "همسایگی اقامتگاه",
  ROOMS_INFO: "اطلاعات اتاق خواب و سرویس ها",
  PROPERTY_FACILITIES: "امکانات ملک",
  REST_ROOMS: "سرویس بهداشتی",
  SHOWER: "حمام",
  POOL_STATUS: "وضعیت استخر",
  ENTERTAINMENT: "امکانات تفریحی",
  POOL_TYPE: "نوع استخر",
  KITCHEN_ACC: "امکانات آشپزخانه",
  KITCHEN: " آشپزخانه",
  COOL_HEAT: "امکانات سرمایشی و گرمایشی",
  WELFARE: "امکانات رفاهی",
  OTHER_ACCESSES: "سایر امکانات",
  CAPS_N_PRICES: "ظرفیت و قیمت ها",
  COMITION_PERC: "درصد کمیسیون مشاور",
  REND_DAYLI_PRICE: "قیمت اجاره روزانه",
  SHOW_OWNERS_PHONE: "نمایش شماره مالک بر روی آگهی",
  SHOW_ASSISTANT_PHONE: "نمایش شماره دستیار بر روی آگهی",
  SHOW_BOTH_PHONE: "نمایش هر دو شماره بر روی آگهی",
  ASSISTANT_PHONE: "شماره تلفن دستیار ",
  ASSISTANT_NAME: "نام و نام خانوادگی دستیار",
  STRICT_RULER: "سخت گیرانه",
  NORMAL_RULER: "سهل گیرانه",
  EASY_RULER: "متعادل",
  GUEST_TYPE_STATUS: "شرایط پذیرش نوع میهمان",
  MORE_DESC: "توضیحات بیشتر (اختیاری)",
  DESCRIPTION_DOTS: "توضیحات ...",
  ANIMAL_RULES: "شرایط ورود حیوان خانگی",

  PARTY_RULES: "شرایط برگزاری مراسم",
  ACCOMMODATION_RULES: "مقررات اقامتگاه",
  PARTY: "امکان برگزاری مراسم",
  PET: "امکان ورود حیوان خانگی",
  REQUIRED_DOCS: "مدارک مورد نیاز جهت پذیرش ",

  PROP_DESC: "درباره اقامتـگاه",
  OTHER_DESC: "سایر توضیحات",
  CANCEL_OTHER_DESC: "توضیحات لغو رزرو (کنسلی)",
  CANCELATIONS_TITLE: "انتخاب نوع قوانین لغو درخواست میهمان (کنسلی)",
  SUBMIT_PROPERTY: "ثبت ملک",
  UR_PROP_REGISTERED: "اطلاعات ملک شما ثبت شد!",

  UR_PROP_REGISTERED_DESC: "پس از پرداخت هزینه و بررسی همکاران ما منتشر خواهد شد",
  YES: "بله",
  NO: "نه",
  VIEW_STATS: "آمار بازدید ملک در یک هفته گذشته",
  PAYABLE_AMOUNT: "هزینه قابل پرداخت",
  COST: "هزینه",
  FILTERS: "فیلتر ها",
  EMPTY_LIST: " موردی ثبت نشده است",
  HAS_POOL: "استخردار",
  NO_POOL: "بدون استخر",
  TODAY_STATUS: "وضعیت امروز",
  GUEST_CAP: "ظرفیت میهمان ها",
  STANDARD_GUEST_CAP: "ظرفیت استاندارد میهمان ",
  MAX_GUEST_CAP: "حداکثر ظرفیت پذیرش میهمان",
  EXTRA_COSTS: "هزینه های مازاد",
  GUEST_CAP_AND_EXTRA_COSTS: "ظرفیت میهمان و هزینه مازاد",
  RENT_TYPE: "نوع اجاره",
  PROP_RENT_TYPE: "نوع اجاره ملک",
  DAYLI_RENT_PRICE: "قیمت اجاره روزانه",
  WEEK_STARTER_DAYS_PRICE: "قیمت شنبه تا سه شنبه",
  WEEK_WENSDAY_PRICE: "قیمت چهارشنبه",
  WEEK_THURSDAY_PRICE: "قیمت پنجشنبه",
  WEEK_FRIDAY_PRICE: "قیمت جمعه",
  WEEK_PEAK_PRICE: "قیمت ایام پیک",
  CLEANING_PRiCE: "هزینه نظافت ",
  EXTRA_GUEST_PRICE: "هزینه هر نفر اضافه",
  ACCSESS_ROUTE_DESC: "توضیحات بافت و مسیر دسترسی",
  OTHER_ACCS: "سایر امکانات",
  PROP_NEIGHTBOUR: "همسایگی اقامتگاه",
  DISTANCETO_POINT: "فاصله تا مکان های خاص",
  EXTRA_BED: "رخت خواب اضافه",
  MASTER_ROOM: "اتاق خواب مستر",
  SOFA_BED: "مبل تخت خواب شو",
  HAS: "دارد",
  DOSE_NOT_HAVE: "ندارد",
  WC: "سرویس بهداشتی",
  WC_IR: "سرویس بهداشتی فرنگی",
  WC_INTERNATIONAL: "سرویس بهداشتی ایرانی",
  ALL_SHOWER: "حمام مشترک",
  TUB_SHOWER: "حمام وان دار",
  SHOWE_IN_WC: "حمام در سرویس",
  MASTER_SHOWER: "حمام در اتاق",
  DAILY: "روزانه",
  CANT_FIND: "موردی یافت نشده است",
  UR_SEARCH_HISTORY: "آخرین جستجوهای شما",
  REGISTER: "ثبت نام",

  LOGOUT_TITLE: "خروج از حساب کاربری",

  LOG_OUT_MESSAGE: "آیا مطمئنید که می‌خواهید از حساب کاربری خود خارج شوید؟",

  LOGGING_OUT: "خروج از حساب کاربری",
  ADDS: "آگهی ها",
  CONSULTANTS: "مشاوران",
  ADD_ADD: "ثبت آگهی",
  PLZ_SELECT_A_PAGE: "لطفا صفحه مورد نظر خود را از منوی سمت راست انتخاب کنید .",
  LOGIN_TO_UR_ACCOUNT: "ورود به حساب کاربری",
  ADD_DURATION: "مدت اعتبار آگهی",
  EXTEND_SUBS: "تمدید اعتبار",
  UPGRADE_ADD_DESC: "ارتقای آگهی افزایش بازدید ",
  PROP_CARD_C_DETAILS: "مشاهده جزئیات و ویرایش تقویم",
  SUB_STATUS: "وضعیت اشتراک",
  RESERVED_DAYS: "روز های رزرو شده",
  EMPTY_DAYS: "روز های خالی",
  PEAK_DAYS: "روز های پیک",
  MEMO_DAYS: "روز های دارای یادداشت",
  SELECT_DAYS_TO_GO_ON: "برای تغییر موارد ذیل، یک یا چند روز را از روی تقویم انتخاب کنید.",
  CLEAR_SELECTION: "حذف انتخاب ها",
  SELECT_ONE_DAY_ONLY: "این مورد فقط برای یک روز قابل تغییر است.",
  SELECTED_DAYS_COUNT: "روز انتخاب شده",
  EMPTY_FULL: "پر / خالی",
  CHANGE_PRICE: "تغییر قیمت",
  EDIT_PRICES: "ویرایش قیمت‌ها",
  EDIT_CALENDAR: "ویرایش تقویم",
  COMMISSION: "کمیسیون مشاور",
  MEMO: "یادداشت",
  CHANGE_ADVISOR_COMMISSION: "تغییر کمیسیون مشاور",
  PROP_STATS: "آمار بازدید و ارتقا آگهی",
  REQUEST_FOR_BADGE: "دریافت نشان ممتاز",
  AUTHORiZIATION_REQUEST: "احراز  ملک",
  NATIONAL_CARD_IMAGE: "تصویر کارت ملی",
  DOCS_IMAGES: "تصاویر مدارک (سند, قولنامه و ...)",
  EDIT_INFO: "ویرایش اطلاعات",
  MESSAGE_TEXT: "متن پیام",
  IMAGES: "تصاویر",
  CHAT: "چت",
  CHAT_INPUT_PLACEHOLDER: "پیام خود را بنویسید ...",
  COPY_SUCCESS: "رونوشت پیام انجام شد",
  COPY: "رونوشت ",
  DELETED_MESSAGE: "پیام حذف شده",
  CHAT_IN_JAYAB: "چت در جایاب",
  CONTACT_INFO: "اطلاعات تماس",
  ARE_U_SURE_DELETE_MESSAGE: "آیا از حذف پیام مطمئنید",
  MESSAGES: "پیام ها",
  WEEKLY_INQUERY: "استعلام هفتگی",
  ARE_U_SURE_DELETE_PROPERTY: "آیا از حذف آگهی ملک خود مطمئنید ؟",
  ARE_U_SURE_DELETE_PROPERTY_TITLE: "حذف آگهی",
  SHARE_PROP_MESSAGE:
    "توجه: قبل از تنظیم کارت استعلام هفتگی، روزهای رزرو شده ملک خود را از روی تقویم مشخص نمایید. مالک عزیز، این کارت به‌طور خودکار روزهای پر و خالی ملک شما در هفته جاری را علامت‌گذاری نموده و یک گیفت تبلیغاتی با عکس آگهی شما می‌سازد. شما می‌توانید با اشتراک‌گذاری این کارت، استعلام روزهای پر و خالی ملک خود را برای همکاران یا مشتریان خود ارسال نمایید.",
  LOGIN_MODAL_TITLE: "ورود به حساب",
  LOGIN_MODAL_DESC: "برای ادامه نیاز است وارد حساب کاربری خود شوید",
  LOGIN_SUBMIT_YES: "ورود به حساب",
  NOW_NOW: "فعلا نه",
  MODAL_IMAGE_ZOOM: "برای مشاهده تصویر بزرگتر دو بار بر روی آن بزنید ",
  CONTINUE: "ادامه",
  SELECT_ACTIVE_CITIES: "انتخاب شهرهای حوزه فعالیت",
  NATIONAL_CODE: "کدملی",
  TELEPHONE_NUMBER: "شماره تلفن ثابت",
  CITY_CODE: "کد شهر",
  STATIONERY_PLACE: "محل سکونت",
  ADDRESS_DOCS_IMAGES: "تصویر مدرک احراز محل سکونت *",
  UPLOAD_RENTAL_DOC: "بارگزاری تصویر سند یا اجاره نامه یا قولنامه",

  REFRAL_CODE: "کد معرف",
  ACTIVITY_FIELD: "حوزه فعالیت",
  SELECT_PROVE: "انتخاب استان",
  SELECT_PROVE_CITY: "انتخاب استان/شهر",
  SELECT_CITY: "انتخاب شهر",
  PROV_LISTS: "لیست استان ها",
  CITY_LISTS: "لیست شهرهای استان",
  SEARCH_DESTINY: "جستجوی مقصد",
  SEARCH_REGION: "جستجوی محله",
  SELECTED_CITIES: "شهر های انتخاب شده",
  REGISTER_ADVISOR: "ثبت نام مشاور",
  ADD_REVIEW_ADVISOR: "ثبت امتیاز مشاور",
  DO_THE_FILTERING: "اعمال فیلتر ها",
  ROOM_COUNT: "تعداد خواب",
  PPL_COUNT: "تعداد نفرات",
  HAS_DISCOUNT: "تخفیف دار",
  PERMIUM_PROPS: "ملک های ویژه",
  FAST_SEARCH: "جستجوی سریع",
  MOST_VISITED_CITIES: "شهر های پربازدید",
  MOST_VISITED_DESTINATIONS: "مقاصد پرطرفدار",

  SHOW_MORE: "نمایش بیشتر",
  COORDINATES: "موقعیت مکانی",
  PROP_TERMS: "قوانین اقامتگاه",
  PROP_TERMS_PROLUGE: "قوانین و شرایطی که میهمان ها باید بپذیرند و در طول اقامتشان آنها را رعایت کنند",
  CANCENLATION_DESC: "قوانین لغو درخواست میهمان (کنسلی)",
  OTHER_TERMS: "سایر قوانین لازم جهت اقامت",
  CONTACT_US: "تماس با ما",
  CONTACT_WAYS: "راه های ارتباطی",
  SEE_ALL: "مشاهده همه",

  OTHER_ARTICLS: "مقالات دیگر",

  SEE_CITIES: "مشاهده شهرها",

  SEND_NEW_TICKET: "ارسال تیکت  جدید",
  CLOSED: "بسته شده",
  WAITING_TO_RESPOND: "در انتظار پاسخ",
  RESPONDED: "پاسخ داده شده",
  JUST_MESSAGE: "پیام",
  SEND: "ارسال",
  TICKET_TITLE: "عنوان تیکت",
  SEND_TICKET: "ارسال تیکت",
  TICKET_TEXT: "متن تیکت",
  SELECT_TIME_WINDOW: "انتخاب بازه زمانی",
  SEND_INFO: "ارسال اطلاعات",
  ADMIN_RESPOND: "پاسخ ادمین :",
  PRICE_RANGE: "بازه قیمت",
  MY_NOTIFS: "اعلان های من",
  DISCOUNT_BIGGER_THAN_PRICE: "قیمت با تخفیف، باید کمتر از قیمت اصلی باشد.",
  REGISTER_AS_SPECIAL_AD: "ثبت نام مشاور ویژه",
  EXPIRES_IN: "اشتراک شما رو به اتمام است",
  EXPIRED: "اشتراک شما  به اتمام رسیده است",
  CITIES: "شهرها",
  RELATED_RESULTS: "جستجوهای مرتبط",
  DESTINATIONS: "مقاصد",
  SEARCH_CITY_OR_ADD: "جستجوی شهر یا آگهی",
  CONFIRM_CODE: "تایید موبایل",
  WAITING_FOR_PAYMENT: "در انتظار پرداخت",

  REMOVE_FILTERS: "حذف همه",
  SUBMIT: "تایید",
  ENTER_HOUR: "ساعت ورود",
  END_HOUR: "ساعت خروج",
  IS_RESERVED: "رزرو شده",
  ANSWER_MESSAGE: "پاسخ به پیام",
  WRITE_MESSAGE_TEXT: "متن پیام را بنویسید",
  TICKET_CLOSED: "تیکت بسته شده است",
  WATCH: "مشاهده",
  COMMIS_JUST_PERC: "درصد کمیسیون",
  END_CONSULT_SUB: "لغو اشتراک",
  SELECT_YOUR_IMAGE: "انتخاب تصویر مورد نظر",
  COMIISH_RANGE_PERC: "بازه درصد کمیسیون",
  INVITE_TEXT: "جایاب را به دوستان و آشنایان خود معرفی کنید تا آنها نیز در تجربه شما شریک باشند",
  EXIT: "خروج",
  ERASE: "پاک کردن",
  VERIFY_PROP: "احراز ملک",
  VERIFY_PROP_MODAL_TEXT: "به منظور عملکرد بهتر و افزایش بازدید، لطفا در اسرع وقت ملک خود احراز کنید.",
  NEXT_MONTH: "ماه بعد",
  LAST_MONTH: "ماه قبل",

  NAVIGATE: "مسیر یابی",
  ADDS_LIST: "لیست آگهی ها",
  REPORT_WRONG: "گزارش تخلف",
  RECAPTHCA_ERROR: "کد امنیتی وارد شده صحیح نمی‌باشد",
  ASK_QUESTION_TITLE: "سوال خود را بپرسید",
  ASK_QUESTION_NAME: "",
  ASK_QUESTION_NAME_PLACEHOLDER: "نام و نام خانوادگی",
  ASK_QUESTION_PHONE: "",
  ASK_QUESTION_PHONE_PLACEHOLDER: "شماره تماس",
  ASK_QUESTION_DESCRIPTION: "متن سوال",
  WHAT_U_GONNA_READ: "آنچه در این مقاله میخوانید:",

  ASK_QUESTION_DESCRIPTION_PLACEHOLDER: "متن سوال",
  ASK_QUESTION_CAPTCHA: "کد امنیتی",
  ASK_QUESTION_SUBMIT: "ارسال",
  LADDERED: "نردبان شده",
  TITLE_PLACEHOLDER: "مثال: کلبه سوئیسی در جنگل , ویلا استخردار در رامسر",

  hOW_MUCH_DO_U_WANT_TO_COMM:
    "اگر مشاورین املاک اقامتگاه شما را اجاره دهند، دوست دارید به آنها چند درصد کمیسیون بدهید ؟",
  HOST: "میزبان",
  NATIONAL_CARD_IMAGE_AUTH: "تصویر کارت ملی شخص آگهی دهنده",
  DOCS_IMAGE_AUTH: "تصویر سند یا اجاره نامه و یا فیش آب یا برق به همراه تصویر کارت ملی مالک نامبرده در سند",
  EMPTY_CONTACT_LIST: "محدودیت نمایش اطلاعات تماس",
  SHOW_FULL_NUMBER: "نمایش کامل شماره تماس",
  ROOM_EXPIRED_NOTICE: "محات اعتبار آگهی شما به اتمام رسیده است",
  LATER: "فعلا نه",
  ROOM_STATS: " آمار بازدید آگهی در یک هفته گذشته",
  LOCAL: "محله",
  SELECT_LOCAL: "انتخاب محله",
  SUBMIT_REPORT: "ثبت گزارش",
  YOUR_REPORT: "گزارش شما",
  REPORT_TITLE: "عنوان گزارش",
  REPORT_ADD: "گزارش آگهی",
  RESERVE: "رزرو",
  START_DATE: "تاریخ ورود",
  EXIT_DATE: "تاریخ خروج",
  TRIP_DATE: "تاریخ سفر",
  SMS: "پیامک",
  DURATION: "به مدت",
  SELECT_DATE: "انتخاب تاریخ",
  SELECT_DATE_SPAN: "انتخاب بازه تاریخی",
  RESERVEE_EXPIRE: "اعتبار رزرو",
  RESERVE_ANSWER_DEADLINE_PASSED:
    "مهلت پاسخ میزبان به پایان رسیده است؛ درخواست شما تا ۲۴ ساعت فعال می‌ماند.",
  REQUEST_STATUS: "وضعیت درخواست",
  YOUR_CALL_CLICKS: " تعداد کیلیک روی دکمه تماس",
  OWNER_PLZ_CALL_MSG: "میزبان گرامی ; تمامی رزرو ها پس از ارتباط و تماس مستقیم با میهمان قطعی میگردد.",
  CANT_RESERVE_MESSAGE: "فعلا امکان صدور درخواست جدید ندارین مگر اینکه درخواست درحال انجام رو کنسل کنین.",
  SUBMIT_RESERVE: " ارسال درخواست رزرو",
  REQUEST_TYPE: "نوع درخواست",
  REQUEST_DATE: "تاریخ ثبت درخواست",
  SEE_DETAILS: "مشاهده جزئیات",
  HOME_TITLE: "اجاره بی‌واسطه ویلا و اقامتگاه",
  ADD_IMAGE_WARNING:
    "میزبان محترم عکس پروفایل شما برای مهمانان قابل مشاهده خواهد بود. لطفاً تصویری مناسب و واضح از چهره خود بارگذاری نمائید. از قرار دادن تصاویر نامرتبط و کارت شناسایی یا مدارک رسمی خودداری کنید.",
  ENVIRONMENT_DESCRIPTION:
    "مثال: این ویلا در محیطی بسیار دنج و آرام با ویویی جنگلی واقع شده است. بخشی از مسیر خاکی و دارای شیب تند می‌باشد.",
  PLACES_DESCRIPTION:
    "مثال: فاصله تا نانوایی و سوپر مارکت ۳۰۰ متر می‌باشد. اولین مرکز خرید و مرکز گردشگری در فاصله ۵۰۰ متری است. فاصله تا ساحل و دریا ده دقیقه می‌باشد.",
  ABOUT_PROPERTY_DESCRIPTION:
    "مثال: این اقامتگاه ساحلی در یک مجموعه بومگردی ۵ واحدی واقع شده است. هر واحد دارای دو اتاق خواب دو نفره و یک اتاق خواب کودک می‌باشد.هر واحد در این اقامتگاه ساحلی دارای سرویس و حمام مجزا می‌باشد.اقامتگاه دارای نگهبانی ۲۴ ساعته است. برای افزایش امنیت شما ورودی‌ها و حیاط دارای دوربین مداربسته می‌باشد.",
  /////////////NEW-FACE//////////////
  FAST_ACCESS: "دسترسی سریع",
  COMUNICATION_WAYS: "راه‌های ارتباطی",
  POOL_LESS: "بدون استخر",
  SUBMIT_DO: "اعمال",
  DELETE_CIIES: "حذف شهرها",
  WATCH_ALL: "نمایش  بیشتر",
  SEE_LESS: "نمایش  کمتر",
  TOMAN_PER_NIGHT: "تومان/شب",
  DATE_IS_FILLED: "این تاریخ رزرو شده.",
  SORT_BY: "مرتب سازی",
  PLACE_DESC_MAND: "توضیحات درباره اقامتگاه الزامیست.",
  FOR_SUPPORT_LOGIN: "برای درخواست پشتیبانی وارد حساب کاربری خود شوید.",
  HI: "سلام",
  NEW: "جدید",
};

export default _STRINGS;
