import { DESTRUCTION } from "dns";
import { property } from "lodash";

const _STRINGS = {
  CURRENCY: "تومان",
  NO_PRICE: "توافقی",
  TOMAN: "تومان",
  BUCKS: "دلار",
  ALL: "همه",
  MINUTES: "دقیقه",
  HOURS: "ساعت",
  RIAL: "ریال",
  ENTER: "ورود",
  ADAD: "عدد",
  NAFAR: "نفر",
  DESTRUCTION: "توضیحات",
  MINUTE: "دقیقه",
  HOUR: "ساعت",
  FROM: "از",
  TO: "تا",
  EMAIL: "ایمیل ",
  UNIT: "واحد ",
  PRICE: "قیمت",
  METER: "متر",
  KM: "کیلومتر",
  SPECIALIST: "متخصص",
  SEARCH: "جستجو",
  COUNT: "تعداد",
  HOME: "خانه",
  GENDER: "جنسیت",
  ADD: "آگهی",
  COUNTRY: "کشور",
  JUST_DEPOSIT: "واریز",
  JUST_WITHDRAW: "برداشت",
  TRANSACTIONS: "تراکنش ها",
  MENU: "منو",
  DELETE: "حذف",
  REPLY: "پاسغ",
  MAN: "مرد",
  WOMAN: "زن",
  DATE: "تاریخ",
  TIME: "زمان",
  DETAILS: "جزئیات",
  UNDERSTOOD: "متوجه شدم",
  ENTER_AND_MOVE_ON: "تایید و ادامه",
  FAVS: "علاقمندی ها",
  NODATA_LIST: "آیتمی یافت نشد",
  SHORT_CODE: "کد کامل نمیباشد",
  TOTAL_NAME: "نام و نام خانوادگی",
  NATIONAL_ID: "کد ملی",
  LOREM:
    "   لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهایتنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری موجودر ارائه راهکارها و شرایط سخت تایپ به پایان رسد.",
  MY_PROFILE: "جایاب من",
  CONNECTING: "در حال اتصال",
  WRONG_NUMBER: " شماره موبایل صحیح نمیباشد",
  ATTENTION: "توجه",
  WORNG_NUMBER: "شماره موبایل صحیح نمیباشد .",
  TERMS: "قوانین و مقررات",
  ENTER_TOUR_MOBILE_NUMBER: "شماره تلفن خود را وارد کنید",
  U_ACCEPTED: "ورود شما به معنای پذیرش",
  SEND_AGAIN: "ارسال مجدد",
  CODE_EXPI_TIME: "اعتبار کد",
  ENTER_FOUR_DIGITS: "کد 4 رقمی ارسال شده به شماره خود را وارد کنید",
  EDIT_NUMBER: "ویرایش شماره",
  CREATE_ADD: "ثبت آگهی",
  CONSULTAMCY: "مشاوران",

  TODAYS_PRICE: "قیمت امروز:",
  VERIFIED: "احراز شده",
  ROOM_COUNTS: "تعداد اتاق:",
  ROOM: "اتاق",
  ROOM_SIZE: "متراژ بنا",
  PROPERTY_LOC: "لوکیشن بنا",
  ONLINE_RESERVE: "رزرو ویلا",
  PERSONAL_INFO: "اطلاعات شخصی",
  YOUR_IMAGE: "عکس شما*",
  PROFILE_IMAGE: " تصویر پروفایل",
  CHECK_CREDENTIOALS: "احراز کد ملی و ادامه",
  REGISTER_PROPERTY: "ثبت ملک",
  PROPERTY_TYPE: "نوع ملک  ",
  ROTATE_PHONE: "لطفا گوشی خود را در حالت عمودی قرار دهید",
  ADD_TITLE: "عنوان آگهی",
  LAND_AREA: "متراژ زمین",
  PROPERTY_AREA: "متراژ بنا ",
  FLOOR_COUNT: "تعداد طبقات ",
  UNITS_IN_FLOOR: "تعداد واحد در طبقات ",
  FLOOR: "طبقه",
  OWNERSHIP_TYPE: "نوع مالکیت  ",
  PROVINCE: "استان",
  CITY: "شهر",
  CREATED_AT_YEAR: "سال ساخت ",
  BUILDING_DIRECTION: "جهت ساختمان  ",
  EXACT_ADDRESS: "آدرس دقیق ",
  CAN_CHAT_SET: "فعال کردن امکان چت",
  LOC_ACCESS: "نمایش موقعیت مکانی به متقاضیان",
  SUBMIT_MOVE_ON: "ثبت و ادامه",
  SELECTED_ADDRESSES: "آدرس های منتخب",
  SEARCH_PLACE: "جستجوی آدرس...",
  SEARCH_PLACE_INPUT: "جستجوی آدرس",
  PROPERTY_LOCATION: "موقعیت مکانی ملک",
  PROPERTY_MEDIA: "تصاویر و ویدئو ملک",
  PRIMARY_IMAGE: "عکس اصلی",
  FEATURE_IMAGE_NEEDED: "لطفا عکس اصلی را انتخاب کنید.",
  ENV_PATTERN: "بافت محیطی",
  ACCESS_ROUTE: "مسیر دسترسی",
  ACCESS_ROUTE_DESC: "توضیحات بافت و مسیر دسترسی",
  NEIGHBORHOOD_TYPE: "همسایگی اقامتگاه",
  ROOMS_INFO: "اطلاعات اتاق خواب و رخت خواب",
  REST_ROOMS: "سرویس بهداشتی",
  SHOWER: "حمام",
  POOL_STATUS: "وضعیت استخر",
  ENTERTAINMENT: "امکانات تفریحی",
  POOL_TYPE: "نوع استخر",
  KITCHEN_ACC: "امکانات آشپزخانه",
  COOL_HEAT: "امکانات سرمایشی و گرمایشی",
  WELFARE_TITLE: "امکانات رفاهی",
  OTHER_ACCESSES: "سایر امکانات",
  CAPS_N_PRICES: "ظرفیت و قیمت ها",
  COMITION_PERC: "درصد کمیسیون مشاور",
  REND_DAYLI_PRICE: "قیمت اجاره روزانه",
  SHOW_OWNERS_PHONE: "نمایش شماره مالک بر روی آگهی",
  SHOW_ASSISTANT_PHONE: "نمایش شماره دستیار بر روی آگهی",
  SHOW_BOTH_PHONE: "نمایش هر دو شماره بر روی آگهی",
  ASSISTANT_PHONE: "شماره تلفن دستیار ",
  ASSISTANT_NAME: "نام و نام خانوادگی دستیار",
  STRICT_RULER: "سخت گیرانه",
  NORMAL_RULER: "سهل گیرانه",
  EASY_RULER: "متعادل",
  GUEST_TYPE_STATUS: "شرایط پذیرش نوع میهمان",
  MORE_DESC: "توضیحات بیشتر (اختیاری)",
  DESCRIPTION_DOTS: "توضیحات ...",
  ANIMAL_RULES: "شرایط ورود حیوان خانگی",

  PARTY_RULES: "شرایط برگزاری مراسم",
  REQUIRED_DOCS: "مدارک مورد نیاز جهت پذیرش (اختیاری)",

  PROP_DESC: "توضیحات ملک",
  OTHER_DESC: "سایر توضیحات",
  CANCELATIONS_TITLE: "انتخاب نوع قوانین لغو درخواست میهمان (کنسلی)",
  SUBMIT_PROPERTY: "ثبت ملک",
};

export default _STRINGS;
