export interface ImageDto {
  id: number;
  user_id: null;
  admin_id: number;
  name: string;
  meta: null;
  thumbnail: string;
  type: number;
  path: string;
  bucket: string;
  region: null;
  end_point: string;
  medium: string;
  alt: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
}

export type SendOtpDto = { mobile_number: string | number | null };
export type SendForgetOtpDto = { auth_param: string | number | null; forget_type: string | null };
export type ConfirmForgetOtpDto = {
  auth_param: string | number | null;
  forget_type: string | null;
  code: string | null;
};
export type SendOtpType = { code: number };
export type SendOtpVerify = { mobile_number: number | null | string; code: number | null | string };
export type SendOtpVerifyResponse = { auth_token?: string; access_token?: string; socket_token?: string };
export type CheckUserName = { username: string };
export type CheckUserNameResponse = any;
export type SetPassword = { username?: string; password: string | null; password_confirm: string | null };
export type SetNewPassword = {
  password: string | null;
  password_confirm: string | null;
  auth_param: string | null;
  forget_type: string;
  code: string;
};
export type SetDetailResponse = any;
export type SetDetail = {
  birthday: { year: string | number | null; month: string | number | null; day: string | number | null } | null;
  profile_image_id: string | number | null;
  city_id: string | number | null;
  full_name: string | number | null;
};
export type SetPasswordResponse = any;
export type SignInDTO = {
  password: string | number | null;
  auth_param: string | number | null;
};
export type SignInResponseDTO = any;

// Generated by https://quicktype.io

export interface ForgetasswordListDto {
  [key: string]: string | null;
}

// Generated by https://quicktype.io

export interface Member {
  national_code: string;
  ancestor_name: string;
  birthday: string;
  profile: Profile;
  telephone_number: string;
  city: City;
  home_address: string;
  work_address: string;
  created_at: string;
}

export interface City {
  id: number;
  title: string;
}

export interface Profile {
  id: number;
  user_id: number;
  admin_id: null;
  name: string;
  meta: null;
  thumbnail: string;
  type: number;
  path: string;
  bucket: string;
  region: null;
  end_point: string;
  medium: string;
  alt: null;
  created_at: string;
  updated_at: string;
  deleted_at: null;
}

export type UpdateProfileDto = {
  full_name: string;
};
export type UpdateStepTwoProfileDto = {
  national_code: string;
  ancestor_name?: string;
  birthday: { year: string; month: string; day: string };
  profile_id: number;
  city_id: number | null;
  telephone_number: string;
  work_address?: string;
  home_address: string;
};

// Generated by https://quicktype.io

export interface RegisterDto {
  user: User;
  access_token: string;
}

export interface User {
  id: number;
  mobile_number: string;
  full_name: string;
  father_name: string;
  gender: number;
  is_show: boolean;
  can_see_members: boolean;
  member_id: null;
  deceased_info_id: null;
  fcm_token: null;
  jwt_level: number;
  notification_read_at: string;
  created_at: string;
  updated_at: string;
}

// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface CitiesDto {
  id: number;
  title: string;
  child: Child[];
}

export interface Child {
  id: number;
  title: string;
}

// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface DefaultAddressDto {
  id: number;
  user_id: number;
  title: string;
  address: string;
  address_detail: string;
  lat: number;
  lng: number;
  recipient_full_name: string;
  recipient_phone_number: string;
  postal_code: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
}

// Generated by https://quicktype.io

export interface InnitSettingsDto {
  isMarketplace: boolean;
  googleTagManagerId: string;
  hasProductAttribute: boolean;
}

export interface GetProfileDto {
  id: number;
  mobile_number: string;
  full_name: string;
  profile_image: string;
  owner_id: string;
  advisor_id: string;
  created_at: Date;
}
