import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { debounce } from "lodash";

// import { savedLoc } from "@/utils/faker";
import FormInput from "@/components/shared/Form/FormInput";
import PopUpDown from "../PopUpDown";
import getAddresses from "./SearchAddress";
import SearchedLocItem from "./SearchedLocItem";

// Generated by https://quicktype.io

export interface SearchedLOCType {
  title: string;
  address: string;
  category: string;
  type: string;
  region: string;
  neighbourhood: string;
  location: Location;
}

export interface Location {
  x: number;
  y: number;
  z: string;
}

const SearchPlaceModal = ({
  show,
  setShow,
  title,
  center,
  setJumpTo,
}: {
  show: boolean;
  setShow: (e: boolean) => void | null;
  title: string;
  center: number[];
  setJumpTo: React.Dispatch<
    React.SetStateAction<{
      lat: string | number;
      lng: string | number;
    } | null>
  >;
}) => {
  const [isTyping, setIsTyping] = useState(false);
  const [search, setSearch] = useState("");
  const [searchedAddresses, setSearchedAddresses] = useState<any[]>([]);
  const [firstTime, setFirstTime] = useState(true);
  const [loading, setLoading] = useState(false);
  const checkTyping = useCallback(
    debounce(() => {
      setIsTyping(false);
      setFirstTime(false);
    }, 1000),
    [],
  );

  const handleChange = (v: string) => {
    setSearch(v);
    setIsTyping(true);
    checkTyping();
  };

  useMemo(() => {
    if (search.length >= 0 && !isTyping && !firstTime) {
      setTimeout(
        () =>
          getAddresses({
            search: search,
            setSearchedAddress: setSearchedAddresses,
            setSearchedAddressLoading: setLoading,
            center,
          }),
        1000,
      );
    }
  }, [search, isTyping]);

  const closeFunc = () => {
    setShow(false);
  };
  const locationClickFunc = (e: SearchedLOCType) => {
    setJumpTo({ lat: e?.location?.y, lng: e?.location?.x });
    // setSelectedAddress(e?.address);
    closeFunc();
  };

  useEffect(() => {
    if (show) {
      setTimeout(() => {
        inputRef.current?.focus();
      }, 500);
    }
  }, [show]);

  const inputRef = useRef<HTMLInputElement>(null);
  return (
    <PopUpDown item={{ title: title, popHieghtType: "full-height" }} visible={show} setVisible={closeFunc}>
      <div className="w-full h-full flex flex-col gap-6 bg-white rounded-xl p-4">
        <FormInput
          value={search}
          onChangeText={(e) => handleChange(e)}
          item={{
            placeholder: title,
            containerClass: "w-full !relative",
            iconUrl: "/assets/icons/edit/magnifier.svg",
            iconUrlClassName: "!w-4 !top-[32%]",
            id: 1,
            passedRef: inputRef,
          }}
        />
        <div className="flex flex-col gap-4    items-center pb-8 ">
          {searchedAddresses?.length == 0 ? (
            <>
              {/* <p className="font-light w-full  text-start text-xs">{_STRINGS?.A13}</p>

              {savedLoc?.map((e) => (
                <div
                  key={`savedLoc${e?.id}`}
                  onClick={() => {
                    locationClickFunc(e?.lat, e?.lng);
                  }}
                  className="w-full p-4 border-b border-gray-1000 flex items-center gap-4"
                >
                  <img src="/assets/icons/shared/primary_location.svg" />
                  <p>{e?.title}</p>
                </div>
              ))} */}
            </>
          ) : (
            <>
              {/* <p className="text-base text-start w-full mb-4">{"_STRINGS.MAP_SEARCHED_ITEMS_TITLE"}</p> */}
              {searchedAddresses?.map((e: SearchedLOCType, index: number) => (
                <SearchedLocItem
                  item={e}
                  locationClickFunc={locationClickFunc}
                  key={`searchedLoc${e?.category}${e?.title}${index}`}
                />
              ))}
            </>
          )}
        </div>
      </div>
    </PopUpDown>
  );
};

export default SearchPlaceModal;
